export const menuItems = [
  {
    id: 1,
    name: "Cappuccino",
    shortDesc: "Classic espresso with steamed milk and velvety foam.",
    longDesc:
      "A rich blend of bold espresso, silky steamed milk, and a thick layer of velvety foam — a timeless café favorite crafted for perfect balance.",
    image: "https://images.pexels.com/photos/350478/pexels-photo-350478.jpeg",
    price: 54,
    category: "Hot Coffee",
    rating: 4.9,
    available: true,
    ingredients: ["Espresso", "Steamed Milk", "Foam"],
    calories: 120,
    prepTime: 4,
    isSpecial: true,
    tags: ["Best Seller", "Creamy"],
    stock: 25,
    sold: 140,
    discount: 0,
  },

  {
    id: 2,
    name: "Latte",
    shortDesc: "Smooth espresso blended with creamy steamed milk.",
    longDesc:
      "A smooth and creamy harmony of espresso and steamed milk, offering a mild, comforting, and perfectly balanced coffee experience.",
    image: "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg",
    price: 49,
    category: "Hot Coffee",
    rating: 4.8,
    available: true,
    ingredients: ["Espresso", "Milk", "Foam"],
    calories: 180,
    prepTime: 3,
    isSpecial: false,
    tags: ["Popular"],
    stock: 30,
    sold: 120,
    discount: 5,
  },

  {
    id: 3,
    name: "Americano",
    shortDesc: "Bold espresso diluted with hot water.",
    longDesc:
      "Bold espresso softened with hot water, preserving its deep aroma and smooth, robust flavor — simple, pure, and satisfying.",
    image: "https://images.pexels.com/photos/34085/pexels-photo.jpg",
    price: 39,
    category: "Hot Coffee",
    rating: 4.7,
    available: true,
    ingredients: ["Espresso", "Hot Water"],
    calories: 10,
    prepTime: 2,
    isSpecial: false,
    tags: ["Strong"],
    stock: 40,
    sold: 100,
    discount: 0,
  },

  {
    id: 4,
    name: "Mocha",
    shortDesc: "Espresso with chocolate and steamed milk.",
    longDesc:
      "A delicious blend of espresso, rich chocolate, and steamed milk, topped with fluffy whipped cream for a sweet, indulgent treat.",
    image: "https://images.pexels.com/photos/982612/pexels-photo-982612.jpeg",
    price: 62,
    category: "Hot Coffee",
    rating: 5.0,
    available: true,
    ingredients: ["Espresso", "Chocolate", "Milk", "Whipped Cream"],
    calories: 320,
    prepTime: 5,
    isSpecial: true,
    tags: ["Chocolate", "Sweet", "Top Rated"],
    stock: 15,
    sold: 200,
    discount: 10,
  },

  {
    id: 6,
    name: "Caramel Frappé",
    shortDesc: "Icy caramel-blended coffee topped with cream.",
    longDesc:
      "A refreshing blend of espresso, crushed ice, milk, and caramel syrup — finished with whipped cream for a cool, sweet, and energizing delight.",
    image:
      "https://images.pexels.com/photos/22882240/pexels-photo-22882240.jpeg",
    price: 65,
    category: "Cold Coffee",
    rating: 4.8,
    available: true,
    ingredients: ["Espresso", "Ice", "Milk", "Caramel Syrup"],
    calories: 350,
    prepTime: 6,
    isSpecial: false,
    tags: ["Cold", "Sweet"],
    stock: 20,
    sold: 180,
    discount: 5,
  },

  {
    id: 7,
    name: "Iced Latte",
    shortDesc: "Cold milk over espresso poured on ice.",
    longDesc:
      "Fresh espresso poured over chilled milk and ice, delivering a smooth, refreshing, and lightly creamy iced coffee experience.",
    image: "https://images.pexels.com/photos/434213/pexels-photo-434213.jpeg",
    price: 55,
    category: "Cold Coffee",
    rating: 4.7,
    available: true,
    ingredients: ["Espresso", "Cold Milk", "Ice"],
    calories: 120,
    prepTime: 3,
    isSpecial: false,
    tags: ["Refreshing"],
    stock: 35,
    sold: 160,
    discount: 0,
  },

  {
    id: 8,
    name: "Matcha Latte",
    shortDesc: "Whisked matcha blended with warm milk.",
    longDesc:
      "Ceremonial-grade matcha whisked into warm milk to create a vibrant green latte with subtle earthy sweetness and calming energy.",
    image: "https://images.pexels.com/photos/4725593/pexels-photo-4725593.jpeg",
    price: 55,
    category: "Tea & Latte",
    rating: 4.9,
    available: true,
    ingredients: ["Matcha", "Milk", "Hot Water"],
    calories: 140,
    prepTime: 4,
    isSpecial: true,
    tags: ["Green Tea", "Healthy"],
    stock: 10,
    sold: 90,
    discount: 0,
  },

  {
    id: 9,
    name: "Chai Latte",
    shortDesc: "Spiced tea blended with steamed milk.",
    longDesc:
      "A cozy blend of black tea and warm spices like cinnamon and cardamom, mixed with steamed milk for a soothing and aromatic drink.",
    image: "https://images.pexels.com/photos/5946617/pexels-photo-5946617.jpeg",
    price: 42,
    category: "Tea & Latte",
    rating: 4.8,
    available: true,
    ingredients: ["Black Tea", "Milk", "Cinnamon", "Cardamom"],
    calories: 160,
    prepTime: 4,
    isSpecial: false,
    tags: ["Spicy"],
    stock: 25,
    sold: 110,
    discount: 0,
  },

  {
    id: 10,
    name: "Croissant",
    shortDesc: "Flaky, buttery, golden pastry.",
    longDesc:
      "A perfectly baked, golden-brown croissant that is buttery, flaky, and irresistibly light — a classic bakery delight.",
    image: "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg",
    price: 30,
    category: "Pastry",
    rating: 4.9,
    available: true,
    ingredients: ["Butter", "Flour", "Sugar"],
    calories: 250,
    prepTime: 2,
    isSpecial: false,
    tags: ["Bakery", "Light"],
    stock: 20,
    sold: 130,
    discount: 0,
  },

  {
    id: 11,
    name: "Chocolate Muffin",
    shortDesc: "Rich muffin with dark chocolate chunks.",
    longDesc:
      "A soft and moist chocolate muffin filled with rich dark chocolate chunks, offering deep cocoa flavor in every bite.",
    image: "https://images.pexels.com/photos/227432/pexels-photo-227432.jpeg",
    price: 32,
    category: "Pastry",
    rating: 5.0,
    available: true,
    ingredients: ["Cocoa", "Flour", "Sugar", "Chocolate"],
    calories: 300,
    prepTime: 2,
    isSpecial: true,
    tags: ["Sweet", "Chocolate"],
    stock: 18,
    sold: 150,
    discount: 5,
  },

  {
    id: 12,
    name: "Brownie",
    shortDesc: "Rich, fudgy chocolate brownie.",
    longDesc:
      "A dense and fudgy brownie with a crisp top layer — deeply chocolatey, moist, and perfectly indulgent for dessert lovers.",
    image:
      "https://images.pexels.com/photos/45202/brownie-dessert-cake-sweet-45202.jpeg",
    price: 35,
    category: "Dessert",
    rating: 4.8,
    available: true,
    ingredients: ["Chocolate", "Butter", "Sugar", "Cocoa"],
    calories: 320,
    prepTime: 3,
    isSpecial: false,
    tags: ["Dessert", "Chocolate"],
    stock: 12,
    sold: 140,
    discount: 0,
  },
];
