export const menuItems = [
  {
    id: 1,
    name: "Cappuccino",
    desc: "A timeless favorite — rich espresso balanced with steamed milk and a thick layer of velvety foam. Perfectly smooth, aromatic, and ideal for those who love a creamy texture with a hint of espresso strength.",
    image: "https://images.pexels.com/photos/350478/pexels-photo-350478.jpeg",
    price: "$54",
    category: "Hot Coffee",
    rating: 4.9,
    available: true,
    size: ["S", "M", "L"],
  },
  {
    id: 2,
    name: "Latte",
    desc: "A smooth blend of espresso and creamy steamed milk, topped with delicate foam. Balanced in flavor and body, our Latte is crafted to be comforting and mellow — a daily dose of coziness in every sip.",
    image: "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg",
    price: "$49",
    category: "Hot Coffee",
    rating: 4.8,
    available: true,
    size: ["S", "M", "L"],
  },
  {
    id: 3,
    name: "Americano",
    desc: "For coffee purists, this bold and clean beverage combines rich espresso with hot water, preserving the coffee’s aroma and full-bodied flavor while keeping it refreshingly light.",
    image: "https://images.pexels.com/photos/34085/pexels-photo.jpg",
    price: "$39",
    category: "Hot Coffee",
    rating: 4.7,
    available: true,
    size: ["S", "M", "L"],
  },
  {
    id: 4,
    name: "Mocha",
    desc: "An indulgent fusion of espresso, chocolate, and steamed milk, topped with whipped cream and cocoa powder. A decadent treat for chocolate lovers who crave the rich harmony of sweetness and caffeine.",
    image: "https://images.pexels.com/photos/982612/pexels-photo-982612.jpeg",
    price: "$59",
    category: "Hot Coffee",
    rating: 5.0,
    available: true,
    size: ["M", "L"],
  },
  {
    id: 5,
    name: "Cold Brew",
    desc: "Brewed slowly over 16 hours for a smooth, low-acid finish. Our Cold Brew delivers deep, chocolatey undertones and a naturally sweet, refreshing flavor — ideal for warm afternoons.",
    image: "https://images.pexels.com/photos/1442533/pexels-photo-1442533.jpeg",
    price: "$60",
    category: "Cold Coffee",
    rating: 4.9,
    available: true,
    size: ["M", "L"],
  },
  {
    id: 6,
    name: "Caramel Frappé",
    desc: "A creamy blend of espresso, crushed ice, milk, and caramel syrup, finished with whipped cream and a drizzle of golden caramel. Sweet, cold, and irresistibly smooth — a dessert in a cup!",
    image:
      "https://images.pexels.com/photos/22882240/pexels-photo-22882240.jpeg",
    price: "$65",
    category: "Cold Coffee",
    rating: 4.8,
    available: true,
    size: ["M", "L"],
  },
  {
    id: 7,
    name: "Iced Latte",
    desc: "Espresso poured over ice with chilled milk for a refreshing twist on a classic favorite. Light, creamy, and smooth — a perfect balance between coffee flavor and cool refreshment.",
    image: "https://images.pexels.com/photos/434213/pexels-photo-434213.jpeg",
    price: "$55",
    category: "Cold Coffee",
    rating: 4.7,
    available: true,
    size: ["S", "M", "L"],
  },
  {
    id: 8,
    name: "Matcha Latte",
    desc: "A calming blend of ceremonial-grade matcha green tea and steamed milk. Naturally sweet, earthy, and vibrant — a beautiful balance between smooth creaminess and herbal freshness.",
    image: "https://images.pexels.com/photos/4725593/pexels-photo-4725593.jpeg",
    price: "$55",
    category: "Tea & Latte",
    rating: 4.9,
    available: true,
    size: ["S", "M", "L"],
  },
  {
    id: 9,
    name: "Chai Latte",
    desc: "A cozy fusion of black tea, warm spices, and steamed milk, with hints of cinnamon, cardamom, and cloves. The perfect drink to comfort your soul and awaken your senses.",
    image: "https://images.pexels.com/photos/5946617/pexels-photo-5946617.jpeg",
    price: "$49",
    category: "Tea & Latte",
    rating: 4.8,
    available: true,
    size: ["S", "M", "L"],
  },
  {
    id: 10,
    name: "Croissant",
    desc: "Flaky, buttery, and golden — our croissants are baked fresh every morning. The crisp layers melt in your mouth, making it a delightful partner for any coffee or tea.",
    image: "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg",
    price: "$30",
    category: "Pastry",
    rating: 4.9,
    available: true,
    size: [],
  },
  {
    id: 11,
    name: "Chocolate Muffin",
    desc: "A rich, moist muffin packed with premium cocoa and dark chocolate chunks. Soft on the inside and slightly crisp on top — every bite satisfies your chocolate craving.",
    image: "https://images.pexels.com/photos/227432/pexels-photo-227432.jpeg",
    price: "$32",
    category: "Pastry",
    rating: 5.0,
    available: true,
    size: [],
  },
  {
    id: 12,
    name: "Tiramisu",
    desc: "Our handcrafted tiramisu combines espresso-soaked ladyfingers with layers of rich mascarpone cream and a dusting of cocoa. Light, creamy, and decadently smooth — Italy’s finest dessert experience.",
    image: "https://images.pexels.com/photos/302680/pexels-photo-302680.jpeg",
    price: "$70",
    category: "Dessert",
    rating: 5.0,
    available: true,
    size: [],
  },
  {
    id: 13,
    name: "Brownie",
    desc: "Thick, fudgy brownies baked to perfection with a crisp top and gooey chocolate center. The perfect blend of sweetness and richness for true chocolate lovers.",
    image:
      "https://images.pexels.com/photos/45202/brownie-dessert-cake-sweet-45202.jpeg",
    price: "$35",
    category: "Dessert",
    rating: 4.8,
    available: true,
    size: [],
  },
  {
    id: 14,
    name: "Affogato",
    desc: "A luxurious Italian dessert drink — creamy vanilla ice cream ‘drowned’ in a shot of freshly brewed espresso. Sweet, hot, and cold all at once — a sensory delight in every spoonful.",
    image: "https://images.pexels.com/photos/1310133/pexels-photo-1310133.jpeg",
    price: "$60",
    category: "Dessert",
    rating: 4.9,
    available: true,
    size: [],
  },
];
